// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { Toaster } from "react-hot-toast";
// import { PlayerProvider } from "@/context/PlayerContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Cross Over | Scouting",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html>
//       <body>
//         <PlayerProvider>
//           {children}
//           <Toaster position="top-center" reverseOrder={false} />

//         </PlayerProvider>
//       </body>
//     </html>
//   );
// }

// layout.jsx
import ClientWrapper from "@/components/ClientWrapper";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Cross Over | Scouting",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html>
    <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientWrapper>{children}
             <Toaster position="top-center" reverseOrder={false} />

        </ClientWrapper>
      </body>
    </html>
  );
}
